[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ast = true
ffi = true  # 添加这行启用 FFI
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read-write", path = "./"}]

solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
